name: Build and Sign APK

on:
  push:
    branches: [ "main", "dev-*", "prd-*", "master", "development", "ravit" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Decode keystore (base64 -w 0 should have been used when encoding)
      - name: Decode and Save Keystore
        run: echo "${{ secrets.KEYSTORE_BASE_64 }}" | base64 --decode > app/rerng_app.jks

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Install Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      # Accept SDK Licenses
      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses || true
          mkdir -p $ANDROID_HOME/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license

      # Install SDK components
      - name: Install SDK Components
        run: sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # Make gradlew executable
      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      # Build signed release APK
      - name: Build signed APK
        run: ./gradlew assembleRelease

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
