name: Android CI Build

on:
  push:
    branches: [ "dev-*", "prd-*", "master", "development", "ravit" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Decode keystore from secrets and save it to the project
      - name: Decode and Save Keystore
        env:
          KEYSTORE_BASE_64: ${{ secrets.KEYSTORE_BASE_64 }}
        run: echo "$KEYSTORE_BASE_64" | base64 -d > app/rerng_app.jks

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Install Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      # Accept Android SDK licenses
      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses || true
          mkdir -p $ANDROID_HOME/licenses
          echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license

      # Install necessary SDK components
      - name: Install SDK Components
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # Grant execute permissions to Gradle wrapper
      - name: Grant Gradle Permissions
        run: chmod +x ./gradlew

      # Build Release APK (this uses the keystore for signing)
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Upload APK artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
