name: Android CI Build

on:
  push:
    branches:
      - "dev-*"
      - "prd-*"
      - "master"
      - "development"
      - "ravit"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK Command-line Tools
        run: |
          yes | sdkmanager --install "cmdline-tools;latest"
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Accept Android Licenses
        run: |
          mkdir -p $ANDROID_HOME/licenses
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license

      - name: Install Android SDK Components
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build APK (Release)
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk