name: Android CI Build

on:
  push:
    branches:
      - "dev-*"
      - "prd-*"

jobs:
  build:
    name: Build VisitMe APK
    runs-on: ubuntu-latest  # GitHub-hosted runner

    env:
      ANDROID_HOME: "/sdk"
      GRADLE_USER_HOME: "${{ github.workspace }}/.gradle"

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Decode the keystore from the secrets and store it
      - name: Decode Keystore
        env:
          KEYSTORE_BASE_64: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          echo "$KEYSTORE_BASE_64" | base64 -d > app/rerng_app.jks
          ls -la app/  # List the files to ensure it's saved correctly

      # Install the required Android SDK components
      - name: Install Android SDK
        run: |
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0"

      # Grant execution permissions for Gradle scripts
      - name: Grant permissions for Gradle
        run: chmod +x ./gradlew

      # Run Gradle build to generate the APK
      - name: Run Gradle Build
        run: ./gradlew assembleRelease

      # Debug: Check if the APK exists
      - name: List build output directory
        run: ls -R app/build/outputs/apk/release/

      # Upload the APK if it exists
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: visit-me-apk
          path: app/build/outputs/apk/release/*.apk
